# Generated by Django 5.2 on 2025-04-20 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("tasks", "0002_remove_attachment_task_remove_attachment_uploaded_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="team",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
