# Generated by Django 5.2 on 2025-04-20 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="security_level",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="blocking_tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="task",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="team",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="task",
        ),
        migrations.RemoveField(
            model_name="transcriptionrecord",
            name="tasks_created",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transcriptionrecord",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="AITaskPrediction",
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="SecurityLevel",
        ),
        migrations.DeleteModel(
            name="TaskCategory",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskHistory",
        ),
        migrations.DeleteModel(
            name="TranscriptionRecord",
        ),
    ]
